### ISSUE TITLE
No echo when send command

### ISSUE THREAD

**Issue by Nossolov** [MitchBradley/FluidTerm2#1]
Hello.
Fluidterm2 work well.
Small pb : i dont have any echo on the terminal screen when i write a command with the keyboard on a PC win10, not even "$".
However, after "return", the command is well transmitted and executed.
May be french keyboard ?

**Comment by MitchBradley** [comment]
Type Tab to trigger echo mode on FluidNC.  The new version that I am working on does it automatically.

**Comment by Nossolov** [comment]
Fine : Tab is working.
Thank you.

**Comment by MitchBradley** [comment]
Try the new version.  It does the tab thing automatically.  The only case where you have to type tab manually is after you reset by typing `$bye`.  In that case, fluidterm does not know that a reset has happened so it cannot automatically issue the command to turn on the echoing.

The new version also handles port disconnects, like if you unplug the USB cable.

**Comment by Nossolov** [comment]
New version tested : no more need to send "tab". It's ok.
Now, i try to configure and use Fluidnc with Wemos D1 R32 and CNC shield V3.0
Long way for me ...
